#Redis 配置，以下除了 timeout 外全部为默认配置.
spring:
  redis:
    host: localhost
    port: 6379
    database: 2
    password:
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
