# org.redisson.Config类的配置参数,适用于所有Redis组态模式（单机，集群和哨兵）
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: NIO

# Redis 单机部署时 Redisson 文件方式配置
singleServerConfig:
  address: "redis://127.0.0.1:6379" #节点地址
  password: null #密码,默认null
  database: 15 #数据库编号,默认0
  idleConnectionTimeout: 10000 #连接空闲超时,单位毫秒,默认10000
  connectTimeout: 10000 #连接超时,单位毫秒,默认10000
  timeout: 3000 #命令等待超时,单位毫秒,默认3000
  retryAttempts: 3 #命令失败重试次数,默认3
  retryInterval: 1500 #命令重试发送时间间隔,单位毫秒,默认1500
  subscriptionsPerConnection: 5 #单个连接最大订阅数量,默认5
  clientName: null #客户端名称,默认null,
  subscriptionConnectionMinimumIdleSize: 1 #发布和订阅连接的最小空闲连接数,默认1
  subscriptionConnectionPoolSize: 50 #发布和订阅连接池大小,默认50
  connectionMinimumIdleSize: 32 #最小空闲连接数,默认32
  connectionPoolSize: 64 #连接池大小,默认64
  dnsMonitoringInterval: 5000 #DNS监测时间间隔,单位毫秒,默认5000
  sslEnableEndpointIdentification: true #启用SSL终端识别,默认true
  sslProvider: JDK #SSL实现方式,默认JDK
  sslTruststore: null #SSL信任证书库路径,默认null
  sslTruststorePassword: null #SSL信任证书库密码,默认null
  sslKeystore: null #SSL钥匙库路径,默认null
  sslKeystorePassword: null #SSL钥匙库密码,默认null
